# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75ec3558f2055e566157d416e9bc25e2ef9796125e8a62d1484728c516cbddff777a45aeb45680cde75e4308dca295d4b3fc97f62d40a6e9422758a3237ccc93

test:
  secret_key_base: 4f9385c54273a6df821a86d519570939ce140e5413eb783646f35f37ddefd8e49445a6b9b2df5b711e0171d36299804208abe659dea2707a6237b1c35ae871f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
