# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3d022d2492f4b6bd92f9ba68a15fe27541b8f3604efe46b1b75e009f930e2a01aea5cb7f3b9213b7fc04e5e10dddacddb58d5ac19454b19c9623ecd52ecbb56

test:
  secret_key_base: 64cc0346892b3511243be56020051310e549497e69a967a2088451cce6be1d3e2eda0f13ca0e7e1b6684f27a8c58895dc62aae0a20c6fe72f24d8f53ba116f43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
